kind: ""
apiversion: ""
commonLabels:
    app: idm
resources:
- boot-properties.yaml
- logging-properties.yaml
- configmap.yaml
- statefulset.yaml
- service.yaml
secretGenerator:
- name: idm-secrets
  type: Opaque
  files:
  - secrets/keystore.jceks
  - secrets/truststore
  - secrets/realm.properties