apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: end-user-ui
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: gcr.io/engineering-devops/end-user-ui:fraasEndUserClient
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: end-user-ui
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
