kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-idm
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  #storageClassName: standard
  resources:
    requests:
      storage: 10Gi
