# Deploys to default.iam.forgeops.com. Uses the LE issuer for SSL.
namespace: default
bases:
  - ../../frconfig
  - ../../ds/cts
  - ../../ds/idrepo
  - ../../am
  - ../../amster
  - ../../idm
  - ../../end-user-ui
  - ../../ingress
patchesStrategicMerge:
  - platform-config.yaml