apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: pentest-app
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: pentest-app
        env:
        # - name: OPENIG_BASE
        #   value: /config
        # - name: CATALINA_OPTS
        #   value: -server
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: gcr.io/engineering-devops/pentest-app:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /rest/state
            port: 8080
          periodSeconds: 30
          timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /kube/readiness
        #     port: 8080
        #   initialDelaySeconds: 5
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
