namespace: default
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../base/kustomizeConfig
- ../../base/forgeops-secrets
- ../../base/ds/cts
- ../../base/ds/idrepo
- ../../base/am
- ../../base/amster
- ../../base/idm
- ../../base/ingress
- ../../base/ldif-importer
