apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds
spec:
  selector:
    matchLabels:
      app: ds
  serviceName: ds
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: instance
                      operator: In
                      values:
                        - ds
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - name: restore
          image: ds
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: data
            mountPath: /opt/opendj/data
          - name: backup
            mountPath: /opt/opendj/bak
          - name: secrets
            mountPath: /var/run/secrets/opendj
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          args: [ "restore" ]
          envFrom:
            - configMapRef:
                name: ds
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
      containers:
        - name: ds
          image: ds
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: ds
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            httpGet:
              path: /alive
              port: http
          ports:
            - name: ldap
              containerPort: 1389
            - name: ldaps
              containerPort: 1636
            - name: admin
              containerPort: 4444
            - name: replication
              containerPort: 8989
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
          volumeMounts:
          - mountPath: /opt/opendj/data
            name: data
          - mountPath: /opt/opendj/secrets
            name: secrets
      securityContext:
        fsGroup: 0
        runAsUser: 11111
      terminationGracePeriodSeconds: 30
      volumes:
        - name: secrets
          secret:
            secretName: ds
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: backup
      annotations:
        pv.beta.kubernetes.io/gid: "0"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi